const createDocumentId = (puskesmas, documentType, month, year) => {
  const seed = `${puskesmas}|${documentType}|${month}|${year}`;
  let hash = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return `doc${(hash >>> 0).toString(36)}`;
};

const documentTypes = [
  'Laporan kegiatan edukasi/penyuluhan & senam Prolanis',
  'Fotocopy materi yang disampaikan',
  'Daftar hadir peserta',
  'Foto kegiatan edukasi (penyuluhan) & senam',
  'Full vidio kegiatan yang di upload di IG/youtube FKTP',
  'Kuitansi jasa instruktur/narasumber',
  'Nota pembelian konsumsi',
  'Kuitansi pembelian konsumsi',
  'Kuitansi total tagihan',
  'Fotocopy proposal kegiatan tahun 2025',
  'Formulir Pengajuan Klaim (FPK)',
  'Berita acara serah terima klaim',
  'Surat pengajuan klaim',
  'Surat tanggung jawab mutlak bermaterai',
];

const months = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
];

const puskesmasList = [
  'Mulia Hati 1', 'Mulia Hati 2',
  'Budi Mulia 1', 'Budi Mulia 2',
  'Harapan Kasih 1', 'Harapan Kasih 2',
  'Sentosa 1', 'Sentosa 2',
  'Citra Medika 1', 'Citra Medika 2',
  'Sehat Mandiri 1', 'Sehat Mandiri 2'
];

const years = ['2024', '2025', '2026'];

function checkCollisions() {
  const ids = new Map();
  let total = 0;
  let collisions = 0;
  
  for (const puskesmas of puskesmasList) {
    for (const year of years) {
      const activeMonths = year === '2026' ? ['Januari', 'Februari', 'Maret'] : months;
      for (const month of activeMonths) {
        for (const docType of documentTypes) {
          const id = createDocumentId(puskesmas, docType, month, year);
          total++;
          if (ids.has(id)) {
            collisions++;
            console.log(`COLLISION! ${id} generated by:`);
            console.log(`  1: ${ids.get(id)}`);
            console.log(`  2: ${puskesmas} | ${docType} | ${month} | ${year}`);
          } else {
            ids.set(id, `${puskesmas} | ${docType} | ${month} | ${year}`);
          }
        }
      }
    }
  }
  
  console.log(`Total generated IDs: ${total}`);
  console.log(`Unique IDs count: ${ids.size}`);
  console.log(`Collisions found: ${collisions}`);
}

checkCollisions();
